image: k33g/bots-garden-rust-training:0.0.0

tasks:
  - name: initialize
    before: |

      # ------------------------------------
      # wasmer
      # ------------------------------------
      source /home/gitpod/.wasmer/wasmer.sh
      wasmer --version
      # ------------------------------------
      # wasmtime
      # ------------------------------------
      wasmtime --version
      # ------------------------------------
      # wasmedge dependencies
      # ------------------------------------
      source /home/gitpod/.wasmedge/env
      wasmedge --version

    init: |
      echo "🚀 initialize"
      #npm install


ports:
  - port: 8080
    visibility: public
  - port: 3000
    visibility: public
  - port: 5000
    visibility: public

vscode:
  extensions:
    - pkief.material-icon-theme
    - rust-lang.rust
    - bungcip.better-toml
    - aaron-bond.better-comments

